//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Asteck.SurveyPlus.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuestionnaire
    {
        public int UserId { get; set; }
        public int QuestionnaireId { get; set; }
        public Nullable<bool> IsComplete { get; set; }
    
        public virtual Questionnaire Questionnaire { get; set; }
        public virtual User User { get; set; }
    }
}
